In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
import scipy.optimize as curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Cargamos el archivo csv
dm = pd.read_csv("Florencia_limpio_para_regresion.csv")
dm = dm.drop([ 'Unnamed: 0',], axis=1)
dm.head(5)

host_response_time host_response_rate host_acceptance_rate  \
0      within an hour               100%                 100%   
1      within an hour               100%                  25%   
2  within a few hours               100%                  65%   
3      within an hour               100%                  71%   
4      within an hour               100%                  71%   

  host_is_superhost host_identity_verified        room_type has_availability  \
0                 f                      t     Private room                t   
1                 f                      t  Entire home/apt                t   
2                 f                      t  Entire home/apt                t   
3                 f                      t     Private room                t   
4                 f                      t     Private room                t   

  instant_bookable  host_listings_count  accommodates  beds  price  \
0                t                  6.0           2.0   2.0  257.2   
1                f                  1.0           2.0   1.0   95.0   
2                f                  1.0           4.0   4.0  130.0   
3                f                 10.0           2.0   1.0  105.0   
4                f                 10.0           2.0   2.0  257.2   

   minimum_nights  availability_365  number_of_reviews  review_scores_rating  \
0             1.0               330              133.0                  4.66   
1             1.0                26               26.0                  4.88   
2             6.0               257               36.0                  4.74   
3             2.0               347               79.0                  4.53   
4             2.0               332               21.0                  4.32   

   reviews_per_month  
0               0.77  
1               0.15  
2               0.21  
3               0.46  
4               0.13

Apartado de categorización

*host_response_time*

In [3]:
#Categorizamos la variable "host_response_time", donde 1 = "rápido" y 0 = "lento"
dm["host_response_time"] = dm["host_response_time"].replace({
'within an hour': 1,
'within a few hours': 1,
'within a day': 1,
'a few days or more': 0,
'Sin tiempo': 0,
'Desconocido': 0
})

C:\Users\Miriam Florencia\AppData\Local\Temp\ipykernel_4148\1504478180.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dm["host_response_time"] = dm["host_response_time"].replace({


*host_response_rate*

In [4]:
dm['host_response_rate'] = dm['host_response_rate'].str.replace('%', '', regex=True).astype(float) / 100

*host_acceptance_rate*

In [5]:
dm['host_acceptance_rate'] = dm['host_acceptance_rate'].str.replace('%', '', regex=True).astype(float) / 100

*host_is_superhost*

In [6]:
dm['host_is_superhost'] = dm['host_is_superhost'].replace({'f': 0, 't': 1})

C:\Users\Miriam Florencia\AppData\Local\Temp\ipykernel_4148\77896907.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dm['host_is_superhost'] = dm['host_is_superhost'].replace({'f': 0, 't': 1})


*host_identity_verified*

In [7]:
#Convertimos Los booleanos a números
dm['host_identity_verified'] = dm['host_identity_verified'].replace({'f': 0, 't': 1})

C:\Users\Miriam Florencia\AppData\Local\Temp\ipykernel_4148\4083784908.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dm['host_identity_verified'] = dm['host_identity_verified'].replace({'f': 0, 't': 1})


*room_type*

In [8]:
#categorizamos la variable "room type", donde 1 = "privado" y 0 = "compartido"
dm["room_type"] = dm["room_type"].replace({
'Entire home/apt': 1,
'Private room': 0,
'Shared room': 0,
'Hotel room': 0
})

C:\Users\Miriam Florencia\AppData\Local\Temp\ipykernel_4148\3214663165.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dm["room_type"] = dm["room_type"].replace({


*has_availability*

In [9]:
#Convertimos Los booleanos a números
dm['has_availability'] = dm['has_availability'].replace({'f': 0, 't': 1})

C:\Users\Miriam Florencia\AppData\Local\Temp\ipykernel_4148\391187897.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dm['has_availability'] = dm['has_availability'].replace({'f': 0, 't': 1})


*instant_bookable*

In [10]:
#Convertimos Los booleanos a números
dm['instant_bookable'] = dm['instant_bookable'].replace({'f': 0, 't': 1})

C:\Users\Miriam Florencia\AppData\Local\Temp\ipykernel_4148\2101077878.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dm['instant_bookable'] = dm['instant_bookable'].replace({'f': 0, 't': 1})


*accommodates*

In [11]:
#categorizamos la variable "room type", donde 1 = "privado" y 0 = "compartido"
dm["accommodates"] = dm["accommodates"].replace({
    1: 0,
    2: 0,
    3: 1,
    3.6: 1,
    4: 1,
    5: 1,
    6: 1,
    7: 1
})

*price*

In [12]:
valor_euro=18.50
dm["price_mxn"]=dm["price"] * valor_euro

In [13]:
valor_euro = 18.50
dm["price_mxn"] = dm["price"] * valor_euro

#Categorizamos la variable "price" en 0="barato" y 1="caro"
median_price = dm["price_mxn"].median()
dm["precio"] = (dm["price_mxn"] > median_price).astype(int)

In [14]:
dm["price_mxn"] = dm["price_mxn"].apply(lambda x: 1 if x > 1093 else 0)

*review_scores_rating*

In [15]:
median_rating = dm["review_scores_rating"].median()
dm["review_rating"] = (dm["review_scores_rating"] > median_rating).astype(int)

In [16]:
dm["review_scores_rating"] = dm["review_scores_rating"].apply(lambda x: 1 if x > 4.8 else 0)

Resultados

**instant_bookable**

In [17]:
#Declaración de variables para 'instant bookable'
Vars_Indep_1 = dm[['host_is_superhost', 'host_response_time', 'price_mxn']]
Var_Dep_1 = dm['instant_bookable']

In [18]:
#redefinimos las variables
X_1 = Vars_Indep_1
y_1 = Var_Dep_1

In [19]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.3, random_state=None)

In [20]:
escalar_1 = StandardScaler()
X_train_1 = escalar_1.fit_transform(X_train_1)
X_test_1 = escalar_1.transform(X_test_1)

In [21]:
from sklearn.linear_model import LogisticRegression
algoritmo_1= LogisticRegression()

In [22]:
algoritmo_1.fit(X_train_1,y_train_1)

LogisticRegression()

In [23]:
y_pred_1 = algoritmo_1.predict(X_test_1)
y_pred_1

array([1, 0, 1, ..., 1, 1, 1], shape=(3817,))

In [24]:
from sklearn.metrics import confusion_matrix

matriz_1 = confusion_matrix(y_test_1, y_pred_1)
print('Matriz de Confusión de "instant_bookable" :')
print(matriz_1)

Matriz de Confusión de "instant_bookable" :
[[ 297 1161]
 [ 207 2152]]


In [25]:
from sklearn.metrics import precision_score

precision_1 = precision_score(y_test_1, y_pred_1, average="binary", pos_label=1)
print('Precision del modelo "instant_bookable" :')
print(precision_1)

Precision del modelo "instant_bookable" :
0.6495623302143073


In [26]:
from sklearn.metrics import accuracy_score

exactitud_1= accuracy_score(y_test_1, y_pred_1)
print('Exactitud del modelo "instant_bookable" :')
print(exactitud_1)

Exactitud del modelo "instant_bookable" :
0.6416033534189154


In [27]:
from sklearn.metrics import recall_score

sensibilidad_1= recall_score(y_test_1, y_pred_1, average="binary", pos_label=1)
print('Sensibilidad del modelo "instant_bookable":')
print(sensibilidad_1)

Sensibilidad del modelo "instant_bookable":
0.9122509537939805


**has_availability**

In [28]:
#2.Has availability
Vars_Indep_2 = dm[['availability_365', 'minimum_nights', 'price_mxn']]
Var_Dep_2 = dm['has_availability']

In [29]:
X2 = Vars_Indep_2
y2 = Var_Dep_2

In [30]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(Vars_Indep_2, Var_Dep_2, test_size=0.3, random_state=None)

In [31]:
#Se escalan todos los datos 
escalar_2 = StandardScaler()
X_train_2 = escalar_2.fit_transform(X_train_2)
X_test_2 = escalar_2.transform(X_test_2)

In [32]:
#Definimos el algoritmo a utilizar 
from sklearn.linear_model import LogisticRegression
algoritmo_2 = LogisticRegression()  #le asignamos la importación a una variable

In [33]:
#Entrenamos el modelo 
algoritmo_2.fit(X_train_2, y_train_2)

LogisticRegression()

In [34]:
y_pred_2 = algoritmo_2.predict(X_test_2)
y_pred_2

array([1, 1, 1, ..., 1, 1, 1], shape=(3817,))

In [35]:
from sklearn.metrics import confusion_matrix

matriz_2 = confusion_matrix(y_test_2, y_pred_2)
print('Matriz de Confusión de "has_availability" :')
print(matriz_2)

Matriz de Confusión de "has_availability" :
[[   0    7]
 [   0 3810]]


In [36]:
from sklearn.metrics import precision_score

precision_2 = precision_score(y_test_2, y_pred_2, average="binary", pos_label=1)
print('Precision del modelo "has_availability" :')
print(precision_2)

Precision del modelo "has_availability" :
0.9981660990306523


In [37]:
from sklearn.metrics import accuracy_score

exactitud_2= accuracy_score(y_test_2, y_pred_2)
print('Exactitud del modelo "has_availability" :')
print(exactitud_2)

Exactitud del modelo "has_availability" :
0.9981660990306523


In [38]:
from sklearn.metrics import recall_score

sensibilidad_2= recall_score(y_test_2, y_pred_2, average="binary", pos_label=1)
print('Sensibilidad del modelo "has_availability":')
print(sensibilidad_2)

Sensibilidad del modelo "has_availability":
1.0


**host_is_superhost**

In [39]:
#Declaración de variables para 'host is superhost'
Vars_Indep_3 = dm[['number_of_reviews', 'review_scores_rating', 'host_response_rate']]
Var_Dep_3 = dm['host_is_superhost']

In [40]:
#redefinimos las variables
X_3 = Vars_Indep_3
y_3 = Var_Dep_3

In [41]:
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X_3, y_3, test_size=0.3, random_state=None)

In [42]:
escalar_3 = StandardScaler()
X_train_3 = escalar_3.fit_transform(X_train_3)
X_test_3 = escalar_3.transform(X_test_3)

In [43]:
from sklearn.linear_model import LogisticRegression
algoritmo_3 = LogisticRegression()

In [44]:
algoritmo_3.fit(X_train_3,y_train_3)

LogisticRegression()

In [45]:
y_pred_3 = algoritmo_3.predict(X_test_3)
y_pred_3

array([0, 0, 0, ..., 1, 0, 0], shape=(3817,))

In [46]:
from sklearn.metrics import confusion_matrix

matriz_3 = confusion_matrix(y_test_3, y_pred_3)
print('Matriz de Confusión de "host_is_super_host" :')
print(matriz_3)

Matriz de Confusión de "host_is_super_host" :
[[1540  679]
 [ 397 1201]]


In [47]:
from sklearn.metrics import precision_score

precision_3 = precision_score(y_test_3, y_pred_3, average="binary", pos_label=1)
print('Precision del modelo "host_is_superhost" :')
print(precision_3)

Precision del modelo "host_is_superhost" :
0.6388297872340426


In [48]:
from sklearn.metrics import accuracy_score

exactitud_3= accuracy_score(y_test_3, y_pred_3)
print('Exactitud del modelo "host_is_Superhost" :')
print(exactitud_3)

Exactitud del modelo "host_is_Superhost" :
0.718103222425989


In [49]:
from sklearn.metrics import recall_score

sensibilidad_3= recall_score(y_test_3, y_pred_3, average="binary", pos_label=1)
print('Sensibilidad del modelo "host_is_superhost":')
print(sensibilidad_3)

Sensibilidad del modelo "host_is_superhost":
0.7515644555694618


**host_response_time**

In [50]:
#Declaración de variables para "host response time
Vars_Indep_4 = dm[['host_is_superhost', 'host_response_rate', 'number_of_reviews']]
Var_Dep_4 = dm['host_response_time']

In [51]:
#redefinimos las variables
X_4 = Vars_Indep_4
y_4 = Var_Dep_4

In [52]:
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(X_4, y_4, test_size=0.3, random_state=None)

In [53]:
escalar_4 = StandardScaler()
X_train_4 = escalar_4.fit_transform(X_train_4)
X_test_4 = escalar_4.transform(X_test_4)

In [54]:
from sklearn.linear_model import LogisticRegression
algoritmo_4 = LogisticRegression()

In [55]:
algoritmo_4.fit(X_train_4,y_train_4)

LogisticRegression()

In [56]:
y_pred_4 = algoritmo_4.predict(X_test_4)
y_pred_4

array([1, 1, 1, ..., 1, 1, 1], shape=(3817,))

In [57]:
from sklearn.metrics import confusion_matrix

matriz_4 = confusion_matrix(y_test_4, y_pred_4)
print('Matriz de Confusión de "host_response_time" :')
print(matriz_4)

Matriz de Confusión de "host_response_time" :
[[  65  373]
 [   5 3374]]


In [58]:
from sklearn.metrics import precision_score

precision_4 = precision_score(y_test_4, y_pred_4, average="binary", pos_label=1)
print('Precision del modelo "host_response_time" :')
print(precision_4)

Precision del modelo "host_response_time" :
0.9004536962903656


In [59]:
from sklearn.metrics import accuracy_score

exactitud_4= accuracy_score(y_test_4, y_pred_4)
print('Exactitud del modelo "host_response_time" :')
print(exactitud_4)

Exactitud del modelo "host_response_time" :
0.9009693476552266


In [60]:
from sklearn.metrics import recall_score

sensibilidad_4= recall_score(y_test_4, y_pred_4, average="binary", pos_label=1)
print('Sensibilidad del modelo "host_response_time":')
print(sensibilidad_4)

Sensibilidad del modelo "host_response_time":
0.9985202722699024


**host_identity_verified**

In [61]:
#Declaración de variables para 'price'
Vars_Indep_5 = dm[['host_response_time', 'host_acceptance_rate', 'host_listings_count']]
Var_Dep_5 = dm['host_identity_verified']

In [62]:
#redefinimos las variables
X_5 = Vars_Indep_5
y_5 = Var_Dep_5

In [63]:
X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(X_5, y_5, test_size=0.3, random_state=None)

In [64]:
escalar_5 = StandardScaler()
X_train_5 = escalar_5.fit_transform(X_train_5)
X_test_5 = escalar_5.transform(X_test_5)

In [65]:
from sklearn.linear_model import LogisticRegression
algoritmo_5 = LogisticRegression()

In [66]:
algoritmo_5.fit(X_train_5,y_train_5)

LogisticRegression()

In [67]:
y_pred_5 = algoritmo_5.predict(X_test_5)
y_pred_5

array([1, 1, 1, ..., 1, 1, 1], shape=(3817,))

In [68]:
from sklearn.metrics import confusion_matrix

matriz_5 = confusion_matrix(y_test_5, y_pred_5)
print('Matriz de Confusión de "host_identity_verified" :')
print(matriz_5)

Matriz de Confusión de "host_identity_verified" :
[[   0  143]
 [   0 3674]]


In [69]:
from sklearn.metrics import precision_score

precision_5 = precision_score(y_test_5, y_pred_5, average="binary", pos_label=1)
print('Precision del modelo "host_identity_verified" :')
print(precision_5)

Precision del modelo "host_identity_verified" :
0.962536023054755


In [70]:
from sklearn.metrics import accuracy_score

exactitud_5= accuracy_score(y_test_5, y_pred_5)
print('Exactitud del modelo "host_identity_verified" :')
print(exactitud_5)

Exactitud del modelo "host_identity_verified" :
0.962536023054755


In [71]:
from sklearn.metrics import recall_score

sensibilidad_5= recall_score(y_test_5, y_pred_5, average="binary", pos_label=1)
print('Sensibilidad del modelo "host_identity_verified":')
print(sensibilidad_5)

Sensibilidad del modelo "host_identity_verified":
1.0


**availability_365**

In [72]:
#Declaración de variables para *host identity verified
Vars_Indep_6 = dm[['host_acceptance_rate', 'host_response_time', 'host_listings_count']]
Var_Dep_6 = dm['host_identity_verified']

In [73]:
#redefinimos las variables
X_6 = Vars_Indep_6
y_6 = Var_Dep_6

In [74]:
X_train_6, X_test_6, y_train_6, y_test_6 = train_test_split(X_6, y_6, test_size=0.3, random_state=None)

In [75]:
escalar_6 = StandardScaler()
X_train_6 = escalar_6.fit_transform(X_train_6)
X_test_6 = escalar_6.transform(X_test_6)

In [76]:
from sklearn.linear_model import LogisticRegression
algoritmo_6 = LogisticRegression()

In [77]:
algoritmo_6.fit(X_train_6,y_train_6)

LogisticRegression()

In [78]:
y_pred_6 = algoritmo_6.predict(X_test_6)
y_pred_6

array([1, 1, 1, ..., 1, 1, 1], shape=(3817,))

In [79]:
from sklearn.metrics import confusion_matrix

matriz_6 = confusion_matrix(y_test_6, y_pred_6)
print('Matriz de Confusión de "availability_365" :')
print(matriz_6)

Matriz de Confusión de "availability_365" :
[[   0  127]
 [   0 3690]]


In [80]:
from sklearn.metrics import precision_score

precision_6 = precision_score(y_test_6, y_pred_6, average="binary", pos_label=1)
print('Precision del modelo "availability_365" :')
print(precision_6)

Precision del modelo "availability_365" :
0.9667277966989782


In [140]:
from sklearn.metrics import accuracy_score

exactitud_6= accuracy_score(y_test_6, y_pred_6)
print('Exactitud del modelo "availability_365" :')
print(exactitud_6)

Exactitud del modelo "availability_365" :
0.9667277966989782


In [139]:
from sklearn.metrics import recall_score

sensibilidad_6= recall_score(y_test_6, y_pred_6, average="binary", pos_label=1)
print('Sensibilidad del modelo "availability_365":')
print(sensibilidad_6)

Sensibilidad del modelo "availability_365":
1.0


**room_type**

In [83]:
#Declaración de variables para 'room type
Vars_Indep_7 = dm[['price', 'accommodates', 'beds']]
Var_Dep_7 = dm['room_type']

In [84]:
#redefinimos las variables
X_7 = Vars_Indep_7
y_7 = Var_Dep_7

In [85]:
X_train_7, X_test_7, y_train_7, y_test_7 = train_test_split(X_7, y_7, test_size=0.3, random_state=None)

In [86]:
escalar_7 = StandardScaler()
X_train_7 = escalar_7.fit_transform(X_train_7)
X_test_7 = escalar_7.transform(X_test_7)

In [87]:
from sklearn.linear_model import LogisticRegression
algoritmo_7 = LogisticRegression()

In [88]:
algoritmo_7.fit(X_train_7,y_train_7)

LogisticRegression()

In [89]:
y_pred_7 = algoritmo_7.predict(X_test_7)
y_pred_7

array([1, 1, 1, ..., 1, 1, 1], shape=(3817,))

In [90]:
from sklearn.metrics import confusion_matrix

matriz_7= confusion_matrix(y_test_7, y_pred_7)
print('Matriz de Confusión de "room_type" :')
print(matriz_7)

Matriz de Confusión de "room_type" :
[[  15  635]
 [   6 3161]]


In [91]:
from sklearn.metrics import precision_score

precision_7 = precision_score(y_test_7, y_pred_7, average="binary", pos_label=1)
print('Precision del modelo "room_type" :')
print(precision_7)

Precision del modelo "room_type" :
0.8327186512118019


In [141]:
from sklearn.metrics import accuracy_score

exactitud_7= accuracy_score(y_test_7, y_pred_7)
print('Exactitud del modelo "room_type" :')
print(exactitud_7)

Exactitud del modelo "room_type" :
0.8320670683783076


In [93]:
from sklearn.metrics import recall_score

sensibilidad_7= recall_score(y_test_7, y_pred_7, average="binary", pos_label=1)
print('Sensibilidad del modelo "room_type":')
print(sensibilidad_7)

Sensibilidad del modelo "room_type":
0.998105462582886


**Accommodates**

In [94]:
#Declaración de variables para 'availability_365'
Vars_Indep_8 = dm[['room_type', 'price', 'beds']]
Var_Dep_8 = dm['accommodates']

In [95]:
#redefinimos las variables
X_8 = Vars_Indep_8
y_8 = Var_Dep_8

In [96]:
X_train_8, X_test_8, y_train_8, y_test_8 = train_test_split(X_8, y_8, test_size=0.3, random_state=None)

In [97]:
escalar_8 = StandardScaler()
X_train_8 = escalar_8.fit_transform(X_train_8)
X_test_8 = escalar_8.transform(X_test_8)

In [98]:
from sklearn.linear_model import LogisticRegression
algoritmo_8 = LogisticRegression()

In [99]:
algoritmo_8.fit(X_train_8,y_train_8)

LogisticRegression()

In [100]:
y_pred_8 = algoritmo_8.predict(X_test_8)
y_pred_8

array([1., 1., 1., ..., 1., 1., 0.], shape=(3817,))

In [101]:
from sklearn.metrics import confusion_matrix

matriz_8 = confusion_matrix(y_test_8, y_pred_8)
print('Matriz de Confusión de "accommodates" :')
print(matriz_8)

Matriz de Confusión de "accommodates" :
[[1071  185]
 [ 345 2216]]


In [102]:
from sklearn.metrics import precision_score

precision_8 = precision_score(y_test_8, y_pred_8, average="binary", pos_label=1)
print('Precision del modelo "accommodates" :')
print(precision_8)

Precision del modelo "accommodates" :
0.9229487713452728


In [142]:
from sklearn.metrics import accuracy_score

exactitud_8= accuracy_score(y_test_8, y_pred_8)
print('Exactitud del modelo "accommodates" :')
print(exactitud_8)

Exactitud del modelo "accommodates" :
0.8611474980351062


In [104]:
from sklearn.metrics import recall_score

sensibilidad_8= recall_score(y_test_8, y_pred_8, average="binary", pos_label=1)
print('Sensibilidad del modelo "accommodates":')
print(sensibilidad_8)

Sensibilidad del modelo "accommodates":
0.8652869972666927


**review_scores_rating**

In [105]:
Vars_Indep_9 = dm[['host_is_superhost', 'number_of_reviews', 'reviews_per_month']]
Var_Dep_9 = dm['review_scores_rating']

In [106]:
#redefinimos las variables
X_9 = Vars_Indep_9
y_9 = Var_Dep_9

In [107]:
X_train_9, X_test_9, y_train_9, y_test_9 = train_test_split(X_9, y_9, test_size=0.3, random_state=None)

In [108]:
escalar_9 = StandardScaler()
X_train_9 = escalar_9.fit_transform(X_train_9)
X_test_9 = escalar_9.transform(X_test_9)

In [109]:
from sklearn.linear_model import LogisticRegression
algoritmo_9 = LogisticRegression()

In [110]:
algoritmo_9.fit(X_train_9,y_train_9)

LogisticRegression()

In [111]:
y_pred_9 = algoritmo_9.predict(X_test_9)
# y_pred_9

In [112]:
from sklearn.metrics import confusion_matrix

matriz_9 = confusion_matrix(y_test_9, y_pred_9)
print('Matriz de Confusión de "review_scores_rating" :')
print(matriz_9)

Matriz de Confusión de "review_scores_rating" :
[[1539  422]
 [ 666 1190]]


In [113]:
from sklearn.metrics import precision_score

precision_9 = precision_score(y_test_9, y_pred_9, average="binary", pos_label=1)
print('Precision del modelo "review_scores_rating" :')
print(precision_9)

Precision del modelo "review_scores_rating" :
0.7382133995037221


In [114]:
from sklearn.metrics import accuracy_score

exactitud_1= accuracy_score(y_test_1, y_pred_1)
print('Exactitud del modelo "review_scores_rating" :')
print(exactitud_1)

Exactitud del modelo "review_scores_rating" :
0.6416033534189154


In [115]:
from sklearn.metrics import recall_score

sensibilidad_9= recall_score(y_test_9, y_pred_9, average="binary", pos_label=1)
print('Sensibilidad del modelo "review_scores_rating":')
print(sensibilidad_9)

Sensibilidad del modelo "review_scores_rating":
0.6411637931034483


**price**

In [116]:
#Declaración de variables para 'price'
Vars_Indep_10 = dm[['room_type', 'accommodates', 'review_scores_rating']]
Var_Dep_10 = dm['price_mxn']

In [117]:
#redefinimos las variables
X_10 = Vars_Indep_10
y_10 = Var_Dep_10

In [118]:
X_train_10, X_test_10, y_train_10, y_test_10 = train_test_split(X_10, y_10, test_size=0.3, random_state=None)

In [119]:
escalar_10 = StandardScaler()
X_train_10 = escalar_10.fit_transform(X_train_10)
X_test_10 = escalar_10.transform(X_test_10)

In [120]:
from sklearn.linear_model import LogisticRegression
algoritmo_10 = LogisticRegression()

In [121]:
algoritmo_10.fit(X_train_10,y_train_10)

LogisticRegression()

In [122]:
y_pred_10 = algoritmo_10.predict(X_test_10)
y_pred_10

array([1, 1, 1, ..., 1, 1, 1], shape=(3817,))

In [123]:
from sklearn.metrics import confusion_matrix

matriz_10 = confusion_matrix(y_test_10, y_pred_10)
print('Matriz de Confusión de "price" :')
print(matriz_10)

Matriz de Confusión de "price" :
[[   0  143]
 [   0 3674]]


In [124]:
from sklearn.metrics import precision_score

precision_10 = precision_score(y_test_10, y_pred_10, average="binary", pos_label=1)
print('Precision del modelo "price" :')
print(precision_10)

Precision del modelo "price" :
0.962536023054755


In [143]:
from sklearn.metrics import accuracy_score

exactitud_10= accuracy_score(y_test_10, y_pred_10)
print('Exactitud del modelo "price" :')
print(exactitud_10)

Exactitud del modelo "price" :
0.962536023054755


In [126]:
from sklearn.metrics import recall_score

sensibilidad_10= recall_score(y_test_10, y_pred_10, average="binary", pos_label=1)
print('Sensibilidad del modelo "price":')
print(sensibilidad_10)

Sensibilidad del modelo "price":
1.0


Reemplazar valores

In [127]:
unico_1=np.unique(dm['instant_bookable'])
unico_1

array([0, 1])

In [128]:
dm['instant_bookable']=dm['instant_bookable'].replace([1], "Se puede reservar")
dm

host_response_time  host_response_rate  host_acceptance_rate  \
0                       1                 1.0                  1.00   
1                       1                 1.0                  0.25   
2                       1                 1.0                  0.65   
3                       1                 1.0                  0.71   
4                       1                 1.0                  0.71   
...                   ...                 ...                   ...   
12717                   1                 1.0                  1.00   
12718                   0                 1.0                  1.00   
12719                   0                 1.0                  1.00   
12720                   1                 1.0                  0.97   
12721                   1                 1.0                  1.00   

       host_is_superhost  host_identity_verified  room_type  has_availability  \
0                      0                       1          0                 1   
1                      0                       1          1                 1   
2                      0                       1          1                 1   
3                      0                       1          0                 1   
4                      0                       1          0                 1   
...                  ...                     ...        ...               ...   
12717                  0                       1          1                 1   
12718                  0                       1          1                 1   
12719                  0                       1          1                 1   
12720                  1                       1          1                 1   
12721                  1                       1          1                 1   

        instant_bookable  host_listings_count  accommodates  beds  price  \
0      Se puede reservar                  6.0           0.0   2.0  257.2   
1                      0                  1.0           0.0   1.0   95.0   
2                      0                  1.0           1.0   4.0  130.0   
3                      0                 10.0           0.0   1.0  105.0   
4                      0                 10.0           0.0   2.0  257.2   
...                  ...                  ...           ...   ...    ...   
12717  Se puede reservar                  4.0           1.0   4.0  472.0   
12718  Se puede reservar                  1.0           1.0   3.0  199.0   
12719                  0                  1.0           1.0   3.0   80.0   
12720                  0                  2.0           1.0   2.0  220.0   
12721  Se puede reservar                 12.0           1.0   2.0  104.0   

       minimum_nights  availability_365  number_of_reviews  \
0                 1.0               330              133.0   
1                 1.0                26               26.0   
2                 6.0               257               36.0   
3                 2.0               347               79.0   
4                 2.0               332               21.0   
...               ...               ...                ...   
12717             3.0               310                0.0   
12718             1.0               365                0.0   
12719             2.0               156                0.0   
12720             1.0               364                0.0   
12721             2.0               143                0.0   

       review_scores_rating  reviews_per_month  price_mxn  precio  \
0                         0               0.77          1       1   
1                         1               0.15          1       0   
2                         0               0.21          1       0   
3                         0               0.46          1       0   
4                         0               0.13          1       1   
...                     ...                ...        ...     ...   
12717                     0             

In [129]:
unico_2=np.unique(dm['has_availability'])
unico_2

array([0, 1])

In [130]:
dm['has_availability']=dm['has_availability'].replace([1], "Tiene disponibilidad")
dm

host_response_time  host_response_rate  host_acceptance_rate  \
0                       1                 1.0                  1.00   
1                       1                 1.0                  0.25   
2                       1                 1.0                  0.65   
3                       1                 1.0                  0.71   
4                       1                 1.0                  0.71   
...                   ...                 ...                   ...   
12717                   1                 1.0                  1.00   
12718                   0                 1.0                  1.00   
12719                   0                 1.0                  1.00   
12720                   1                 1.0                  0.97   
12721                   1                 1.0                  1.00   

       host_is_superhost  host_identity_verified  room_type  \
0                      0                       1          0   
1                      0                       1          1   
2                      0                       1          1   
3                      0                       1          0   
4                      0                       1          0   
...                  ...                     ...        ...   
12717                  0                       1          1   
12718                  0                       1          1   
12719                  0                       1          1   
12720                  1                       1          1   
12721                  1                       1          1   

           has_availability   instant_bookable  host_listings_count  \
0      Tiene disponibilidad  Se puede reservar                  6.0   
1      Tiene disponibilidad                  0                  1.0   
2      Tiene disponibilidad                  0                  1.0   
3      Tiene disponibilidad                  0                 10.0   
4      Tiene disponibilidad                  0                 10.0   
...                     ...                ...                  ...   
12717  Tiene disponibilidad  Se puede reservar                  4.0   
12718  Tiene disponibilidad  Se puede reservar                  1.0   
12719  Tiene disponibilidad                  0                  1.0   
12720  Tiene disponibilidad                  0                  2.0   
12721  Tiene disponibilidad  Se puede reservar                 12.0   

       accommodates  beds  price  minimum_nights  availability_365  \
0               0.0   2.0  257.2             1.0               330   
1               0.0   1.0   95.0             1.0                26   
2               1.0   4.0  130.0             6.0               257   
3               0.0   1.0  105.0             2.0               347   
4               0.0   2.0  257.2             2.0               332   
...             ...   ...    ...             ...               ...   
12717           1.0   4.0  472.0             3.0               310   
12718           1.0   3.0  199.0             1.0               365   
12719           1.0   3.0   80.0             2.0               156   
12720           1.0   2.0  220.0             1.0               364   
12721           1.0   2.0  104.0             2.0               143   

       number_of_reviews  review_scores_rating  reviews_per_month  price_mxn  \
0                  133.0                     0               0.77          1   
1                   26.0                     1               0.15          1   
2                   36.0                     0               0.21          1   
3                   79.0                     0               0.46          1   
4                   21.0                     0               0.13          1   
...                  ...                   ...                ...        ...   
12717                0.0                     0               2.00          1   
12718                0.0                     0               2.

In [131]:
unico_3=np.unique(dm['host_is_superhost'])
unico_3

array([0, 1])

In [132]:
dm['host_is_superhost']=dm['host_is_superhost'].replace([1], "El anfitrión es superhost")
dm

host_response_time  host_response_rate  host_acceptance_rate  \
0                       1                 1.0                  1.00   
1                       1                 1.0                  0.25   
2                       1                 1.0                  0.65   
3                       1                 1.0                  0.71   
4                       1                 1.0                  0.71   
...                   ...                 ...                   ...   
12717                   1                 1.0                  1.00   
12718                   0                 1.0                  1.00   
12719                   0                 1.0                  1.00   
12720                   1                 1.0                  0.97   
12721                   1                 1.0                  1.00   

               host_is_superhost  host_identity_verified  room_type  \
0                              0                       1          0   
1                              0                       1          1   
2                              0                       1          1   
3                              0                       1          0   
4                              0                       1          0   
...                          ...                     ...        ...   
12717                          0                       1          1   
12718                          0                       1          1   
12719                          0                       1          1   
12720  El anfitrión es superhost                       1          1   
12721  El anfitrión es superhost                       1          1   

           has_availability   instant_bookable  host_listings_count  \
0      Tiene disponibilidad  Se puede reservar                  6.0   
1      Tiene disponibilidad                  0                  1.0   
2      Tiene disponibilidad                  0                  1.0   
3      Tiene disponibilidad                  0                 10.0   
4      Tiene disponibilidad                  0                 10.0   
...                     ...                ...                  ...   
12717  Tiene disponibilidad  Se puede reservar                  4.0   
12718  Tiene disponibilidad  Se puede reservar                  1.0   
12719  Tiene disponibilidad                  0                  1.0   
12720  Tiene disponibilidad                  0                  2.0   
12721  Tiene disponibilidad  Se puede reservar                 12.0   

       accommodates  beds  price  minimum_nights  availability_365  \
0               0.0   2.0  257.2             1.0               330   
1               0.0   1.0   95.0             1.0                26   
2               1.0   4.0  130.0             6.0               257   
3               0.0   1.0  105.0             2.0               347   
4               0.0   2.0  257.2             2.0               332   
...             ...   ...    ...             ...               ...   
12717           1.0   4.0  472.0             3.0               310   
12718           1.0   3.0  199.0             1.0               365   
12719           1.0   3.0   80.0             2.0               156   
12720           1.0   2.0  220.0             1.0               364   
12721           1.0   2.0  104.0             2.0               143   

       number_of_reviews  review_scores_rating  reviews_per_month  price_mxn  \
0                  133.0                     0               0.77          1   
1                   26.0                     1               0.15          1   
2                   36.0                     0               0.21          1   
3                   79.0                     0               0.46          1   
4                   21.0                     0               0.13          1   
...                  ...                   ...                ...        ...   
12717                0.0                     0 

In [133]:
unico_4=np.unique(dm['host_response_time'])
unico_4

array([0, 1])

In [134]:
dm['host_response_time']=dm['host_response_time'].replace([1], "El tiempo de respuesta es rápido")
dm

host_response_time  host_response_rate  \
0      El tiempo de respuesta es rápido                 1.0   
1      El tiempo de respuesta es rápido                 1.0   
2      El tiempo de respuesta es rápido                 1.0   
3      El tiempo de respuesta es rápido                 1.0   
4      El tiempo de respuesta es rápido                 1.0   
...                                 ...                 ...   
12717  El tiempo de respuesta es rápido                 1.0   
12718                                 0                 1.0   
12719                                 0                 1.0   
12720  El tiempo de respuesta es rápido                 1.0   
12721  El tiempo de respuesta es rápido                 1.0   

       host_acceptance_rate          host_is_superhost  \
0                      1.00                          0   
1                      0.25                          0   
2                      0.65                          0   
3                      0.71                          0   
4                      0.71                          0   
...                     ...                        ...   
12717                  1.00                          0   
12718                  1.00                          0   
12719                  1.00                          0   
12720                  0.97  El anfitrión es superhost   
12721                  1.00  El anfitrión es superhost   

       host_identity_verified  room_type      has_availability  \
0                           1          0  Tiene disponibilidad   
1                           1          1  Tiene disponibilidad   
2                           1          1  Tiene disponibilidad   
3                           1          0  Tiene disponibilidad   
4                           1          0  Tiene disponibilidad   
...                       ...        ...                   ...   
12717                       1          1  Tiene disponibilidad   
12718                       1          1  Tiene disponibilidad   
12719                       1          1  Tiene disponibilidad   
12720                       1          1  Tiene disponibilidad   
12721                       1          1  Tiene disponibilidad   

        instant_bookable  host_listings_count  accommodates  beds  price  \
0      Se puede reservar                  6.0           0.0   2.0  257.2   
1                      0                  1.0           0.0   1.0   95.0   
2                      0                  1.0           1.0   4.0  130.0   
3                      0                 10.0           0.0   1.0  105.0   
4                      0                 10.0           0.0   2.0  257.2   
...                  ...                  ...           ...   ...    ...   
12717  Se puede reservar                  4.0           1.0   4.0  472.0   
12718  Se puede reservar                  1.0           1.0   3.0  199.0   
12719                  0                  1.0           1.0   3.0   80.0   
12720                  0                  2.0           1.0   2.0  220.0   
12721  Se puede reservar                 12.0           1.0   2.0  104.0   

       minimum_nights  availability_365  number_of_reviews  \
0                 1.0               330              133.0   
1                 1.0                26               26.0   
2                 6.0               257               36.0   
3                 2.0               347               79.0   
4                 2.0               332               21.0   
...               ...               ...                ...   
12717             3.0               310                0.0   
12718             1.0               365                0.0   
12719             2.0               156                0.0   
12720             1.0               364                0.0   
12721             2.0               143                0.0   

       review_scores_rating  reviews_per_month  price_mxn  precio  \
0                         0               0.77 

In [135]:
unico_5=np.unique(dm['host_identity_verified'])
unico_5

array([0, 1])

In [136]:
dm['host_identity_verified']=dm['host_identity_verified'].replace(['1'], "El anfitrión está verificado")
dm

host_response_time  host_response_rate  \
0      El tiempo de respuesta es rápido                 1.0   
1      El tiempo de respuesta es rápido                 1.0   
2      El tiempo de respuesta es rápido                 1.0   
3      El tiempo de respuesta es rápido                 1.0   
4      El tiempo de respuesta es rápido                 1.0   
...                                 ...                 ...   
12717  El tiempo de respuesta es rápido                 1.0   
12718                                 0                 1.0   
12719                                 0                 1.0   
12720  El tiempo de respuesta es rápido                 1.0   
12721  El tiempo de respuesta es rápido                 1.0   

       host_acceptance_rate          host_is_superhost  \
0                      1.00                          0   
1                      0.25                          0   
2                      0.65                          0   
3                      0.71                          0   
4                      0.71                          0   
...                     ...                        ...   
12717                  1.00                          0   
12718                  1.00                          0   
12719                  1.00                          0   
12720                  0.97  El anfitrión es superhost   
12721                  1.00  El anfitrión es superhost   

       host_identity_verified  room_type      has_availability  \
0                           1          0  Tiene disponibilidad   
1                           1          1  Tiene disponibilidad   
2                           1          1  Tiene disponibilidad   
3                           1          0  Tiene disponibilidad   
4                           1          0  Tiene disponibilidad   
...                       ...        ...                   ...   
12717                       1          1  Tiene disponibilidad   
12718                       1          1  Tiene disponibilidad   
12719                       1          1  Tiene disponibilidad   
12720                       1          1  Tiene disponibilidad   
12721                       1          1  Tiene disponibilidad   

        instant_bookable  host_listings_count  accommodates  beds  price  \
0      Se puede reservar                  6.0           0.0   2.0  257.2   
1                      0                  1.0           0.0   1.0   95.0   
2                      0                  1.0           1.0   4.0  130.0   
3                      0                 10.0           0.0   1.0  105.0   
4                      0                 10.0           0.0   2.0  257.2   
...                  ...                  ...           ...   ...    ...   
12717  Se puede reservar                  4.0           1.0   4.0  472.0   
12718  Se puede reservar                  1.0           1.0   3.0  199.0   
12719                  0                  1.0           1.0   3.0   80.0   
12720                  0                  2.0           1.0   2.0  220.0   
12721  Se puede reservar                 12.0           1.0   2.0  104.0   

       minimum_nights  availability_365  number_of_reviews  \
0                 1.0               330              133.0   
1                 1.0                26               26.0   
2                 6.0               257               36.0   
3                 2.0               347               79.0   
4                 2.0               332               21.0   
...               ...               ...                ...   
12717             3.0               310                0.0   
12718             1.0               365                0.0   
12719             2.0               156                0.0   
12720             1.0               364                0.0   
12721             2.0               143                0.0   

       review_scores_rating  reviews_per_month  price_mxn  precio  \
0                         0               0.77 

In [137]:
unico_7=np.unique(dm['room_type'])
unico_7

array([0, 1])